// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gdmjttmjjhadltaihpgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkbWp0dG1qamhhZGx0YWlocGdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MTE5MjYsImV4cCI6MjA2OTA4NzkyNn0.5E7CR-pTkz1ri3sW4p289Gjzzm8BUtFNkZWwwvVmfYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);